version: '3.4'

x-envrionment: &environment
  AMQP_URL: amqp://admin:password@rabbitmq:5672
  GCS_BUCKET: vrddt-media
  GCP_PROJECT_ID: vrddt-225521
  GOOGLE_APPLICATION_CREDENTIALS: /vrddt-225521.json
  MONGO_URL: mongodb://admin:password@mongo:27017/vrddt

services:
  consul:
    command: -server -bootstrap -rejoin
    hostname: consul-server
    image: progrium/consul:latest
    networks:
      - vrddt_droplets_net
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
  mongo:
    environment:
      MONGO_INITDB_DATABASE: vrddt
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_USERNAME: admin
    hostname: mongodb-server
    image: mongo
    networks:
      - vrddt_droplets_net
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./config/mongo/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
      - mongodb:/data/db
      - mongodb_config:/data/configdb
  mongo-express:
    environment:
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
    hostname: mongo-express
    image: mongo-express
    networks:
      - vrddt_droplets_net
    ports:
      - "8081:8081"
    restart: always
  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_ERLANG_COOKIE: mycookie
    hostname: rabbitmq-server
    image: rabbitmq:management
    networks:
      - vrddt_droplets_net
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
      # - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"

    # vrddt-api:
    #   environment: *x-environment
    #     FOO: bar
    #   hostname: vrddt-api
    #   image: vrddt-api
    #   networks:
    #     - vrddt_droplets_net
    #   ports:
    #     - "80:80"
    #     - "443:443"
    # links:
    #   - mongo
    #   - rabbitmq

networks:
  vrddt_droplets_net:

volumes:
  mongodb:
  mongodb_config:
  rabbitmq:
    # driver: local
