apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: vrddt-api
  name: vrddt-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: vrddt-api
    spec:
      containers:
      - command:
        - /app/vrddt-api
        - --config
        - /app/config/config.api.toml
        image: johnwyles/vrddt-api:0.0.5
        name: vrddt-api
        ports:
        - containerPort: 9090
        resources: {}
      hostname: vrddt-api
      restartPolicy: Always
status: {}
