[API]
    Address         = ":9090"
    CertFile        = "config/ssl/server.crt"
    GracefulTimeout = 60
    KeyFile         = "config/ssl/server.key"

[Log]
    Format  = "text"
    Level   = "debug"

[Queue]
    Type = "rabbitmq"
    [Queue.RabbitMQ]
        BindingKeyName = "vrddt-bindingkey-converter"
        ExchangeName   = "vrddt-exchange-converter"
    	QueueName      = "vrddt-queue-converter"
    	URI            = "amqp://admin:password@rabbitmq:5672"
    [Queue.Memory]
        MaxSize = 100000

[Store]
    Type = "mongo"
    [Store.Mongo]
        RedditVideosCollectionName = "reddit_videos"
        Timeout                    = 60
    	URI                        = "mongodb://admin:password@mongo:27017/vrddt"
        VrddtVideosCollectionName  = "vrddt_videos"
    [Store.Memory]
        MaxSize = 100000
